#Application Name
spring.application.name=Instagram Backend

#Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Instagram_DB
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#JWT Configuration
spring.security.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#spring.security.jwt.secret=a9G4kP1sT8bV6nQ2Z3mR5yH7uL0xC2w8F6eD4sA2qW8zY1tUN7pK9vB3cM5hJ0rS

spring.security.jtw.expiration=3600000
spring.security.jwt.ACCESS_TOKEN_EXPIRY=900000
spring.security.jwt.REFRESH_TOKEN_EXPIRY= 120000

#Server Configuration
server.port=8080

#actuator Endpoints Configuration
management.endpoints.web.exposure.include=*

#Logging Configuration
logging.level.com.instagram=DEBUG



