version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: instagram-postgres
    environment:
        POSTGRES_DB: Instagram_DB
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 0000
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data

  app:
     build: .
     container_name: instagram-backend
     ports:
        - "8080:8080"
     depends_on:
        - postgres
     environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Instagram_DB
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: 0000
volumes:
    postgres_data: